[project]
name = "lykos"
dynamic = ["version"]
description = "A Python library/CLI tool for fetching *OS firmware keys."
authors = [
    {name = "m1stadev", email = "adamhamdi31@gmail.com"}
]
license = {file = "LICENSE"}
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "loguru>=0.7.2",
    "requests>=2.32.3",
    "click>=8.1.7"
]

[project.urls]
Repository = "https://github.com/m1stadev/lykos"
"Bug Tracker" = "https://github.com/m1stadev/lykos/issues"

[project.scripts]
lykos = "lykos.__main__:main"

[build-system]
requires = ["hatchling", "uv-dynamic-versioning"]
build-backend = "hatchling.build"

[tool.hatch.version]
source = "uv-dynamic-versioning"

[tool.poetry-dynamic-versioning]
vcs = "git"
style = "semver"
dirty = true

[tool.ruff]
target-version = "py39"

[tool.ruff.lint]
extend-select = ["I"]
ignore = ["E722"]

[tool.ruff.format]
quote-style = "single"
